# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_4/bd_3ea7_axi_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_3ea7_axi_crossbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_4/bd_3ea7_axi_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_3ea7_axi_crossbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
