set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0/inst/write_start]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWADDR[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWBURST[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWBURST[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[2]}]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_AWID]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWLEN[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_AWLOCK]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWPROT[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWPROT[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWPROT[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWQOS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWQOS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWQOS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWQOS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[2]}]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_AWUSER]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_AWVALID]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_BREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WDATA[30]}]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_WLAST]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_WVALID]
set_property MARK_DEBUG true [get_nets design_1_i/ps8_0_axi_periph_M00_AXI_AWREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_BRESP[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_BRESP[1]}]
set_property MARK_DEBUG true [get_nets design_1_i/ps8_0_axi_periph_M00_AXI_BVALID]
set_property MARK_DEBUG true [get_nets design_1_i/ps8_0_axi_periph_M00_AXI_WREADY]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_AWREADY]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_BID]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_BRESP[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_BRESP[1]}]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_BUSER]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_BVALID]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0_m00_axi_WREADY]
set_property MARK_DEBUG false [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_AWPROT[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_AWPROT[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_AWPROT[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[3]}]

set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WSTRB[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WSTRB[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WSTRB[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/myip_v1_0_0_m00_axi_WSTRB[2]}]


set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff2]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/zynq_ultra_ps_e_0/inst/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/ps8_0_axi_periph_M00_AXI_BRESP[0]} {design_1_i/ps8_0_axi_periph_M00_AXI_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[0]} {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[1]} {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[2]} {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_WSTRB[0]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[1]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[2]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_WDATA[0]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[1]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[2]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[3]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[4]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[5]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[6]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[7]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[8]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[9]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[10]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[11]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[12]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[13]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[14]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[15]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[16]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[17]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[18]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[19]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[20]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[21]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[22]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[23]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[24]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[25]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[26]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[27]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[28]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[29]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[30]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_BRESP[0]} {design_1_i/myip_v1_0_0_m00_axi_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWLEN[0]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[1]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[2]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[3]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[4]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[5]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[6]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 3 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWPROT[0]} {design_1_i/myip_v1_0_0_m00_axi_AWPROT[1]} {design_1_i/myip_v1_0_0_m00_axi_AWPROT[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWQOS[0]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[1]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[2]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 3 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[0]} {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[1]} {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[0]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[1]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[2]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWBURST[0]} {design_1_i/myip_v1_0_0_m00_axi_AWBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWADDR[0]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[1]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[2]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[3]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[4]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[5]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[6]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[7]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[8]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[9]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[10]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[11]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[12]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[13]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[14]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[15]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[16]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[17]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[18]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[19]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[20]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[21]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[22]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[23]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[24]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[25]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[26]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[27]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[28]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[29]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[30]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWLOCK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWUSER]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BUSER]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/ps8_0_axi_periph_M00_AXI_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/ps8_0_axi_periph_M00_AXI_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/ps8_0_axi_periph_M00_AXI_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/myip_v1_0_0/inst/write_start]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_pl_clk0]
