set_property SRC_FILE_INFO {cfile:/home/y/fpga/axi-test3/axi-test3.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_in_context.xdc rfile:../../../axi-test3.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_1_i/zynq_ultra_ps_e_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/y/fpga/axi-test3/axi-test3.srcs/constrs_1/new/axi-test3.xdc rfile:../../../axi-test3.srcs/constrs_1/new/axi-test3.xdc id:2} [current_design]
current_instance design_1_i/zynq_ultra_ps_e_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0/inst/write_start]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/zynq_ultra_ps_e_0/inst/pl_clk0]]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 160 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_protocol_checker_0/inst/pc_status[0]} {design_1_i/axi_protocol_checker_0/inst/pc_status[1]} {design_1_i/axi_protocol_checker_0/inst/pc_status[2]} {design_1_i/axi_protocol_checker_0/inst/pc_status[3]} {design_1_i/axi_protocol_checker_0/inst/pc_status[4]} {design_1_i/axi_protocol_checker_0/inst/pc_status[5]} {design_1_i/axi_protocol_checker_0/inst/pc_status[6]} {design_1_i/axi_protocol_checker_0/inst/pc_status[7]} {design_1_i/axi_protocol_checker_0/inst/pc_status[8]} {design_1_i/axi_protocol_checker_0/inst/pc_status[9]} {design_1_i/axi_protocol_checker_0/inst/pc_status[10]} {design_1_i/axi_protocol_checker_0/inst/pc_status[11]} {design_1_i/axi_protocol_checker_0/inst/pc_status[12]} {design_1_i/axi_protocol_checker_0/inst/pc_status[13]} {design_1_i/axi_protocol_checker_0/inst/pc_status[14]} {design_1_i/axi_protocol_checker_0/inst/pc_status[15]} {design_1_i/axi_protocol_checker_0/inst/pc_status[16]} {design_1_i/axi_protocol_checker_0/inst/pc_status[17]} {design_1_i/axi_protocol_checker_0/inst/pc_status[18]} {design_1_i/axi_protocol_checker_0/inst/pc_status[19]} {design_1_i/axi_protocol_checker_0/inst/pc_status[20]} {design_1_i/axi_protocol_checker_0/inst/pc_status[21]} {design_1_i/axi_protocol_checker_0/inst/pc_status[22]} {design_1_i/axi_protocol_checker_0/inst/pc_status[23]} {design_1_i/axi_protocol_checker_0/inst/pc_status[24]} {design_1_i/axi_protocol_checker_0/inst/pc_status[25]} {design_1_i/axi_protocol_checker_0/inst/pc_status[26]} {design_1_i/axi_protocol_checker_0/inst/pc_status[27]} {design_1_i/axi_protocol_checker_0/inst/pc_status[28]} {design_1_i/axi_protocol_checker_0/inst/pc_status[29]} {design_1_i/axi_protocol_checker_0/inst/pc_status[30]} {design_1_i/axi_protocol_checker_0/inst/pc_status[31]} {design_1_i/axi_protocol_checker_0/inst/pc_status[32]} {design_1_i/axi_protocol_checker_0/inst/pc_status[33]} {design_1_i/axi_protocol_checker_0/inst/pc_status[34]} {design_1_i/axi_protocol_checker_0/inst/pc_status[35]} {design_1_i/axi_protocol_checker_0/inst/pc_status[36]} {design_1_i/axi_protocol_checker_0/inst/pc_status[37]} {design_1_i/axi_protocol_checker_0/inst/pc_status[38]} {design_1_i/axi_protocol_checker_0/inst/pc_status[39]} {design_1_i/axi_protocol_checker_0/inst/pc_status[40]} {design_1_i/axi_protocol_checker_0/inst/pc_status[41]} {design_1_i/axi_protocol_checker_0/inst/pc_status[42]} {design_1_i/axi_protocol_checker_0/inst/pc_status[43]} {design_1_i/axi_protocol_checker_0/inst/pc_status[44]} {design_1_i/axi_protocol_checker_0/inst/pc_status[45]} {design_1_i/axi_protocol_checker_0/inst/pc_status[46]} {design_1_i/axi_protocol_checker_0/inst/pc_status[47]} {design_1_i/axi_protocol_checker_0/inst/pc_status[48]} {design_1_i/axi_protocol_checker_0/inst/pc_status[49]} {design_1_i/axi_protocol_checker_0/inst/pc_status[50]} {design_1_i/axi_protocol_checker_0/inst/pc_status[51]} {design_1_i/axi_protocol_checker_0/inst/pc_status[52]} {design_1_i/axi_protocol_checker_0/inst/pc_status[53]} {design_1_i/axi_protocol_checker_0/inst/pc_status[54]} {design_1_i/axi_protocol_checker_0/inst/pc_status[55]} {design_1_i/axi_protocol_checker_0/inst/pc_status[56]} {design_1_i/axi_protocol_checker_0/inst/pc_status[57]} {design_1_i/axi_protocol_checker_0/inst/pc_status[58]} {design_1_i/axi_protocol_checker_0/inst/pc_status[59]} {design_1_i/axi_protocol_checker_0/inst/pc_status[60]} {design_1_i/axi_protocol_checker_0/inst/pc_status[61]} {design_1_i/axi_protocol_checker_0/inst/pc_status[62]} {design_1_i/axi_protocol_checker_0/inst/pc_status[63]} {design_1_i/axi_protocol_checker_0/inst/pc_status[64]} {design_1_i/axi_protocol_checker_0/inst/pc_status[65]} {design_1_i/axi_protocol_checker_0/inst/pc_status[66]} {design_1_i/axi_protocol_checker_0/inst/pc_status[67]} {design_1_i/axi_protocol_checker_0/inst/pc_status[68]} {design_1_i/axi_protocol_checker_0/inst/pc_status[69]} {design_1_i/axi_protocol_checker_0/inst/pc_status[70]} {design_1_i/axi_protocol_checker_0/inst/pc_status[71]} {design_1_i/axi_protocol_checker_0/inst/pc_status[72]} {design_1_i/axi_protocol_checker_0/inst/pc_status[73]} {design_1_i/axi_protocol_checker_0/inst/pc_status[74]} {design_1_i/axi_protocol_checker_0/inst/pc_status[75]} {design_1_i/axi_protocol_checker_0/inst/pc_status[76]} {design_1_i/axi_protocol_checker_0/inst/pc_status[77]} {design_1_i/axi_protocol_checker_0/inst/pc_status[78]} {design_1_i/axi_protocol_checker_0/inst/pc_status[79]} {design_1_i/axi_protocol_checker_0/inst/pc_status[80]} {design_1_i/axi_protocol_checker_0/inst/pc_status[81]} {design_1_i/axi_protocol_checker_0/inst/pc_status[82]} {design_1_i/axi_protocol_checker_0/inst/pc_status[83]} {design_1_i/axi_protocol_checker_0/inst/pc_status[84]} {design_1_i/axi_protocol_checker_0/inst/pc_status[85]} {design_1_i/axi_protocol_checker_0/inst/pc_status[86]} {design_1_i/axi_protocol_checker_0/inst/pc_status[87]} {design_1_i/axi_protocol_checker_0/inst/pc_status[88]} {design_1_i/axi_protocol_checker_0/inst/pc_status[89]} {design_1_i/axi_protocol_checker_0/inst/pc_status[90]} {design_1_i/axi_protocol_checker_0/inst/pc_status[91]} {design_1_i/axi_protocol_checker_0/inst/pc_status[92]} {design_1_i/axi_protocol_checker_0/inst/pc_status[93]} {design_1_i/axi_protocol_checker_0/inst/pc_status[94]} {design_1_i/axi_protocol_checker_0/inst/pc_status[95]} {design_1_i/axi_protocol_checker_0/inst/pc_status[96]} {design_1_i/axi_protocol_checker_0/inst/pc_status[97]} {design_1_i/axi_protocol_checker_0/inst/pc_status[98]} {design_1_i/axi_protocol_checker_0/inst/pc_status[99]} {design_1_i/axi_protocol_checker_0/inst/pc_status[100]} {design_1_i/axi_protocol_checker_0/inst/pc_status[101]} {design_1_i/axi_protocol_checker_0/inst/pc_status[102]} {design_1_i/axi_protocol_checker_0/inst/pc_status[103]} {design_1_i/axi_protocol_checker_0/inst/pc_status[104]} {design_1_i/axi_protocol_checker_0/inst/pc_status[105]} {design_1_i/axi_protocol_checker_0/inst/pc_status[106]} {design_1_i/axi_protocol_checker_0/inst/pc_status[107]} {design_1_i/axi_protocol_checker_0/inst/pc_status[108]} {design_1_i/axi_protocol_checker_0/inst/pc_status[109]} {design_1_i/axi_protocol_checker_0/inst/pc_status[110]} {design_1_i/axi_protocol_checker_0/inst/pc_status[111]} {design_1_i/axi_protocol_checker_0/inst/pc_status[112]} {design_1_i/axi_protocol_checker_0/inst/pc_status[113]} {design_1_i/axi_protocol_checker_0/inst/pc_status[114]} {design_1_i/axi_protocol_checker_0/inst/pc_status[115]} {design_1_i/axi_protocol_checker_0/inst/pc_status[116]} {design_1_i/axi_protocol_checker_0/inst/pc_status[117]} {design_1_i/axi_protocol_checker_0/inst/pc_status[118]} {design_1_i/axi_protocol_checker_0/inst/pc_status[119]} {design_1_i/axi_protocol_checker_0/inst/pc_status[120]} {design_1_i/axi_protocol_checker_0/inst/pc_status[121]} {design_1_i/axi_protocol_checker_0/inst/pc_status[122]} {design_1_i/axi_protocol_checker_0/inst/pc_status[123]} {design_1_i/axi_protocol_checker_0/inst/pc_status[124]} {design_1_i/axi_protocol_checker_0/inst/pc_status[125]} {design_1_i/axi_protocol_checker_0/inst/pc_status[126]} {design_1_i/axi_protocol_checker_0/inst/pc_status[127]} {design_1_i/axi_protocol_checker_0/inst/pc_status[128]} {design_1_i/axi_protocol_checker_0/inst/pc_status[129]} {design_1_i/axi_protocol_checker_0/inst/pc_status[130]} {design_1_i/axi_protocol_checker_0/inst/pc_status[131]} {design_1_i/axi_protocol_checker_0/inst/pc_status[132]} {design_1_i/axi_protocol_checker_0/inst/pc_status[133]} {design_1_i/axi_protocol_checker_0/inst/pc_status[134]} {design_1_i/axi_protocol_checker_0/inst/pc_status[135]} {design_1_i/axi_protocol_checker_0/inst/pc_status[136]} {design_1_i/axi_protocol_checker_0/inst/pc_status[137]} {design_1_i/axi_protocol_checker_0/inst/pc_status[138]} {design_1_i/axi_protocol_checker_0/inst/pc_status[139]} {design_1_i/axi_protocol_checker_0/inst/pc_status[140]} {design_1_i/axi_protocol_checker_0/inst/pc_status[141]} {design_1_i/axi_protocol_checker_0/inst/pc_status[142]} {design_1_i/axi_protocol_checker_0/inst/pc_status[143]} {design_1_i/axi_protocol_checker_0/inst/pc_status[144]} {design_1_i/axi_protocol_checker_0/inst/pc_status[145]} {design_1_i/axi_protocol_checker_0/inst/pc_status[146]} {design_1_i/axi_protocol_checker_0/inst/pc_status[147]} {design_1_i/axi_protocol_checker_0/inst/pc_status[148]} {design_1_i/axi_protocol_checker_0/inst/pc_status[149]} {design_1_i/axi_protocol_checker_0/inst/pc_status[150]} {design_1_i/axi_protocol_checker_0/inst/pc_status[151]} {design_1_i/axi_protocol_checker_0/inst/pc_status[152]} {design_1_i/axi_protocol_checker_0/inst/pc_status[153]} {design_1_i/axi_protocol_checker_0/inst/pc_status[154]} {design_1_i/axi_protocol_checker_0/inst/pc_status[155]} {design_1_i/axi_protocol_checker_0/inst/pc_status[156]} {design_1_i/axi_protocol_checker_0/inst/pc_status[157]} {design_1_i/axi_protocol_checker_0/inst/pc_status[158]} {design_1_i/axi_protocol_checker_0/inst/pc_status[159]}]]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_BRESP[0]} {design_1_i/myip_v1_0_0_m00_axi_BRESP[1]}]]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWBURST[0]} {design_1_i/myip_v1_0_0_m00_axi_AWBURST[1]}]]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[0]} {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[1]} {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[2]}]]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[0]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[1]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[2]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[3]}]]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWQOS[0]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[1]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[2]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[3]}]]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWPROT[0]} {design_1_i/myip_v1_0_0_m00_axi_AWPROT[1]} {design_1_i/myip_v1_0_0_m00_axi_AWPROT[2]}]]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWLEN[0]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[1]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[2]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[3]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[4]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[5]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[6]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[7]}]]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWADDR[0]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[1]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[2]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[3]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[4]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[5]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[6]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[7]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[8]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[9]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[10]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[11]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[12]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[13]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[14]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[15]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[16]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[17]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[18]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[19]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[20]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[21]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[22]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[23]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[24]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[25]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[26]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[27]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[28]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[29]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[30]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[31]}]]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_WSTRB[0]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[1]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[2]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[3]}]]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_WDATA[0]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[1]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[2]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[3]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[4]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[5]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[6]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[7]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[8]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[9]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[10]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[11]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[12]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[13]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[14]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[15]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[16]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[17]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[18]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[19]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[20]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[21]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[22]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[23]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[24]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[25]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[26]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[27]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[28]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[29]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[30]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[31]}]]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/<const0>]]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWID]]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWLOCK]]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWREADY]]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWUSER]]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWVALID]]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BID]]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BREADY]]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BVALID]]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WLAST]]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WREADY]]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WUSER]]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WVALID]]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/myip_v1_0_0/inst/write_start]]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
