set_property SRC_FILE_INFO {cfile:/home/y/fpga/axi-test5/axi-test5.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_in_context.xdc rfile:../../../axi-test5.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_1_i/zynq_ultra_ps_e_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/y/fpga/axi-test5/axi-test5.srcs/constrs_1/new/axi.xdc rfile:../../../axi-test5.srcs/constrs_1/new/axi.xdc id:2} [current_design]
current_instance design_1_i/zynq_ultra_ps_e_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0/inst/write_start]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff2]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/zynq_ultra_ps_e_0/inst/pl_clk0]]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/ps8_0_axi_periph_M00_AXI_BRESP[0]} {design_1_i/ps8_0_axi_periph_M00_AXI_BRESP[1]}]]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[0]} {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[1]} {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[2]} {design_1_i/ps8_0_axi_periph_M00_AXI_AWADDR[3]}]]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_WSTRB[0]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[1]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[2]} {design_1_i/myip_v1_0_0_m00_axi_WSTRB[3]}]]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_WDATA[0]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[1]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[2]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[3]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[4]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[5]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[6]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[7]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[8]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[9]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[10]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[11]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[12]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[13]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[14]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[15]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[16]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[17]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[18]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[19]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[20]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[21]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[22]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[23]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[24]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[25]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[26]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[27]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[28]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[29]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[30]} {design_1_i/myip_v1_0_0_m00_axi_WDATA[31]}]]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_BRESP[0]} {design_1_i/myip_v1_0_0_m00_axi_BRESP[1]}]]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWLEN[0]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[1]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[2]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[3]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[4]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[5]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[6]} {design_1_i/myip_v1_0_0_m00_axi_AWLEN[7]}]]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWPROT[0]} {design_1_i/myip_v1_0_0_m00_axi_AWPROT[1]} {design_1_i/myip_v1_0_0_m00_axi_AWPROT[2]}]]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWQOS[0]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[1]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[2]} {design_1_i/myip_v1_0_0_m00_axi_AWQOS[3]}]]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[0]} {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[1]} {design_1_i/myip_v1_0_0_m00_axi_AWSIZE[2]}]]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[0]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[1]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[2]} {design_1_i/myip_v1_0_0_m00_axi_AWCACHE[3]}]]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWBURST[0]} {design_1_i/myip_v1_0_0_m00_axi_AWBURST[1]}]]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/myip_v1_0_0_m00_axi_AWADDR[0]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[1]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[2]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[3]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[4]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[5]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[6]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[7]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[8]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[9]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[10]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[11]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[12]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[13]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[14]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[15]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[16]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[17]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[18]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[19]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[20]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[21]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[22]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[23]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[24]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[25]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[26]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[27]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[28]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[29]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[30]} {design_1_i/myip_v1_0_0_m00_axi_AWADDR[31]}]]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff]]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/myip_v1_0_0/inst/myip_v1_0_M00_AXI_inst/init_txn_ff2]]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWID]]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWLOCK]]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWREADY]]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWUSER]]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_AWVALID]]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BID]]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BREADY]]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BUSER]]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_BVALID]]
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WLAST]]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WREADY]]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/myip_v1_0_0_m00_axi_WVALID]]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/ps8_0_axi_periph_M00_AXI_AWREADY]]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/ps8_0_axi_periph_M00_AXI_BVALID]]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/ps8_0_axi_periph_M00_AXI_WREADY]]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/myip_v1_0_0/inst/write_start]]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_pl_clk0]
