# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0.xci
# IP: The module: 'exdes_rst_processor_1_300M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_rst_processor_1_300M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_rst_processor_1_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_rst_processor_1_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0.xci
# IP: The module: 'exdes_rst_processor_1_300M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_rst_processor_1_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_rst_processor_1_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_rst_processor_1_300M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
