# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/imports/AudioGen.xdc

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/imports/hdmi_acr_ctrl.xdc

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/imports/hdmi_example_zcu106.xdc

# Block Designs: bd/exdes/exdes.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes || ORIG_REF_NAME==exdes} -quiet] -quiet

# IP: bd/exdes/ip/exdes_vid_phy_controller_0/exdes_vid_phy_controller_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_vid_phy_controller_0 || ORIG_REF_NAME==exdes_vid_phy_controller_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_vcc_const_0/exdes_vcc_const_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_vcc_const_0 || ORIG_REF_NAME==exdes_vcc_const_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_tx_video_axis_reg_slice_0/exdes_tx_video_axis_reg_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_tx_video_axis_reg_slice_0 || ORIG_REF_NAME==exdes_tx_video_axis_reg_slice_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_v_hdmi_tx_ss_0/exdes_v_hdmi_tx_ss_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_v_hdmi_tx_ss_0 || ORIG_REF_NAME==exdes_v_hdmi_tx_ss_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_v_hdmi_rx_ss_0/exdes_v_hdmi_rx_ss_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_v_hdmi_rx_ss_0 || ORIG_REF_NAME==exdes_v_hdmi_rx_ss_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_rx_video_axis_reg_slice_0/exdes_rx_video_axis_reg_slice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_rx_video_axis_reg_slice_0 || ORIG_REF_NAME==exdes_rx_video_axis_reg_slice_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_dru_ibufds_gt_odiv2_0/exdes_dru_ibufds_gt_odiv2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_dru_ibufds_gt_odiv2_0 || ORIG_REF_NAME==exdes_dru_ibufds_gt_odiv2_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_gt_refclk_buf_0/exdes_gt_refclk_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_gt_refclk_buf_0 || ORIG_REF_NAME==exdes_gt_refclk_buf_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_vcc_const0_0/exdes_vcc_const0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_vcc_const0_0 || ORIG_REF_NAME==exdes_vcc_const0_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_v_tpg_0/exdes_v_tpg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_v_tpg_0 || ORIG_REF_NAME==exdes_v_tpg_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_gpio_0/exdes_axi_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_axi_gpio_0 || ORIG_REF_NAME==exdes_axi_gpio_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_xbar_0/exdes_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_xbar_0 || ORIG_REF_NAME==exdes_xbar_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_interconnect_0/exdes_axi_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_axi_interconnect_0 || ORIG_REF_NAME==exdes_axi_interconnect_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_clk_wiz_0 || ORIG_REF_NAME==exdes_clk_wiz_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_aud_pat_gen_0/exdes_aud_pat_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_aud_pat_gen_0 || ORIG_REF_NAME==exdes_aud_pat_gen_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes_hdmi_acr_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_hdmi_acr_ctrl_0 || ORIG_REF_NAME==exdes_hdmi_acr_ctrl_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_xbar_1/exdes_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_xbar_1 || ORIG_REF_NAME==exdes_xbar_1} -quiet] -quiet

# IP: bd/exdes/ip/exdes_axi_interconnect_0_0/exdes_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_axi_interconnect_0_0 || ORIG_REF_NAME==exdes_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_xlconcat0_0/exdes_xlconcat0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_xlconcat0_0 || ORIG_REF_NAME==exdes_xlconcat0_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_zynq_us_0/exdes_zynq_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_zynq_us_0 || ORIG_REF_NAME==exdes_zynq_us_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_fmch_axi_iic_0/exdes_fmch_axi_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_fmch_axi_iic_0 || ORIG_REF_NAME==exdes_fmch_axi_iic_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_rst_processor_1_100M_0/exdes_rst_processor_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_rst_processor_1_100M_0 || ORIG_REF_NAME==exdes_rst_processor_1_100M_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_rst_processor_1_300M_0 || ORIG_REF_NAME==exdes_rst_processor_1_300M_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_pc_0/exdes_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_pc_0 || ORIG_REF_NAME==exdes_auto_pc_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_pc_1/exdes_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_pc_1 || ORIG_REF_NAME==exdes_auto_pc_1} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_pc_2/exdes_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_pc_2 || ORIG_REF_NAME==exdes_auto_pc_2} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_pc_3/exdes_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_pc_3 || ORIG_REF_NAME==exdes_auto_pc_3} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_pc_4/exdes_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_pc_4 || ORIG_REF_NAME==exdes_auto_pc_4} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_cc_0/exdes_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_cc_0 || ORIG_REF_NAME==exdes_auto_cc_0} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_pc_5/exdes_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_pc_5 || ORIG_REF_NAME==exdes_auto_pc_5} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_cc_1/exdes_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_cc_1 || ORIG_REF_NAME==exdes_auto_cc_1} -quiet] -quiet

# IP: bd/exdes/ip/exdes_auto_pc_6/exdes_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exdes_auto_pc_6 || ORIG_REF_NAME==exdes_auto_pc_6} -quiet] -quiet

# XDC: bd/exdes/exdes_ooc.xdc
