# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.runs/synth_1/exdes_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.cache/wt [current_project]
set_property parent.project_path /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.5 [current_project]
set_property ip_output_repo /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/hdl/exdes_wrapper.v
add_files /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/exdes.bd
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_vid_phy_controller_0/ip_0/synth/exdes_vid_phy_controller_0_gtwrapper_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_vid_phy_controller_0/ip_0/synth/exdes_vid_phy_controller_0_gtwrapper.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_vid_phy_controller_0/vid_phy_controller_xdc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_vid_phy_controller_0/exdes_vid_phy_controller_0_ooc_fixed.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_vid_phy_controller_0/exdes_vid_phy_controller_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_vid_phy_controller_0/exdes_vid_phy_controller_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_tx_video_axis_reg_slice_0/exdes_tx_video_axis_reg_slice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_tx_video_axis_reg_slice_0/exdes_tx_video_axis_reg_slice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_0/bd_3ea7_v_hdmi_tx_0_core.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_0/bd_3ea7_v_hdmi_tx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_1/bd_3ea7_v_tc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_1/bd_3ea7_v_tc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_2/bd_3ea7_v_axi4s_vid_out_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_2/bd_3ea7_v_axi4s_vid_out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_4/bd_3ea7_axi_crossbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/bd_3ea7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/exdes_v_hdmi_tx_ss_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_3ec1_v_hdmi_rx_0_core.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_3ec1_v_hdmi_rx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_1/bd_3ec1_v_vid_in_axi4s_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_1/bd_3ec1_v_vid_in_axi4s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/bd_3ec1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/exdes_v_hdmi_rx_ss_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rx_video_axis_reg_slice_0/exdes_rx_video_axis_reg_slice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rx_video_axis_reg_slice_0/exdes_rx_video_axis_reg_slice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_dru_ibufds_gt_odiv2_0/exdes_dru_ibufds_gt_odiv2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_dru_ibufds_gt_odiv2_0/exdes_dru_ibufds_gt_odiv2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_gt_refclk_buf_0/exdes_gt_refclk_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_gt_refclk_buf_0/exdes_gt_refclk_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_tpg_0/exdes_v_tpg_0.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_tpg_0/exdes_v_tpg_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_axi_gpio_0/exdes_axi_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_axi_gpio_0/exdes_axi_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_axi_gpio_0/exdes_axi_gpio_0.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_xbar_0/exdes_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_clk_wiz_0/exdes_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_xbar_1/exdes_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_zynq_us_0/exdes_zynq_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_zynq_us_0/exdes_zynq_us_0.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_fmch_axi_iic_0/exdes_fmch_axi_iic_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_fmch_axi_iic_0/exdes_fmch_axi_iic_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_100M_0/exdes_rst_processor_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_100M_0/exdes_rst_processor_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_100M_0/exdes_rst_processor_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_rst_processor_1_300M_0/exdes_rst_processor_1_300M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_pc_0/exdes_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_pc_1/exdes_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_pc_2/exdes_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_pc_3/exdes_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_pc_4/exdes_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_cc_0/exdes_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_cc_0/exdes_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_cc_0/exdes_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_pc_5/exdes_auto_pc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_cc_1/exdes_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_cc_1/exdes_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_cc_1/exdes_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_auto_pc_6/exdes_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/exdes_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top exdes_wrapper -part xczu7ev-ffvc1156-2-e
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef exdes_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file exdes_wrapper_utilization_synth.rpt -pb exdes_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
