# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/exdes_v_hdmi_rx_ss_0.xci
# IP: The module: 'exdes_v_hdmi_rx_ss_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/bd_3ec1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1 || ORIG_REF_NAME==bd_3ec1} -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_3ec1_v_hdmi_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1_v_hdmi_rx_0 || ORIG_REF_NAME==bd_3ec1_v_hdmi_rx_0} -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_1/bd_3ec1_v_vid_in_axi4s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_3ec1_v_vid_in_axi4s_0} -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_2/bd_3ec1_inverter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1_inverter_1_0 || ORIG_REF_NAME==bd_3ec1_inverter_1_0} -quiet] -quiet

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/bd_3ec1_ooc.xdc

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/exdes_v_hdmi_rx_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_v_hdmi_rx_ss_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/exdes_v_hdmi_rx_ss_0.xci
# IP: The module: 'exdes_v_hdmi_rx_ss_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/bd_3ec1.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1 || ORIG_REF_NAME==bd_3ec1} -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_0/bd_3ec1_v_hdmi_rx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1_v_hdmi_rx_0 || ORIG_REF_NAME==bd_3ec1_v_hdmi_rx_0} -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_1/bd_3ec1_v_vid_in_axi4s_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_3ec1_v_vid_in_axi4s_0} -quiet] -quiet

# IP: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/ip/ip_2/bd_3ec1_inverter_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3ec1_inverter_1_0 || ORIG_REF_NAME==bd_3ec1_inverter_1_0} -quiet] -quiet

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/bd_0/bd_3ec1_ooc.xdc

# XDC: /home/y/fpga/v_hdmi_rx_ss_0_ex/v_hdmi_rx_ss_0_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_rx_ss_0/exdes_v_hdmi_rx_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_v_hdmi_rx_ss_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
